source("load_data.R")
png(filename = "plot3.png", width = 480, height = 480)
plot(dt$DateTime, dt$Sub_metering_1, type = "l", xlab = NA, ylab = "Energy sub metering")
lines(dt$DateTime, dt$Sub_metering_2, col = "red")
lines(dt$DateTime, dt$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1)
dev.off()